[package]
edition = "2024"
name = "fdt-edit"
version = "0.1.0"

[dependencies]
log = "0.4"
fdt-raw = {path = "../fdt-raw"}
enum_dispatch = "0.3.13"

[dev-dependencies]
dtb-file = {path = "../dtb-file"}
env_logger = "0.11"
