[package]
authors = ["周睿 <zrufo747@outlook.com>"]
categories = ["embedded", "no-std", "hardware-support"]
description = "A high-level library for creating, editing, and encoding Flattened Device Tree (FDT) structures"
edition = "2024"
homepage = "https://github.com/drivercraft/fdt-parser"
keywords = ["device-tree", "dtb", "embedded", "no-std", "editor"]
license = "MIT OR Apache-2.0"
name = "fdt-edit"
repository = "https://github.com/drivercraft/fdt-parser"
version = "0.2.0"

[dependencies]
fdt-raw = {version = "0.2", path = "../fdt-raw"}
log = "0.4"

[dev-dependencies]
dtb-file.workspace = true
env_logger = "0.11"

[features]
default = []
std = []

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-none-softfloat", "riscv64gc-unknown-none-elf"]
